### PR TITLE
parse_result.py: refactor to produce better html output

### PR DESCRIPTION
**Pull request by aabadie**
This PR improves the html results of Murdock that are produced by the `parse_result.py` script:
- the html result page is split in one main page and on page per application/job type (job type in {compile, run_tests}). 
- the important information are easily accessible from the main page: failed jobs are listed at the beginning, job statistics are in a separate tab, build and run_test jobs have their own tabs
- all html pages are generated using Jinja2 templates, which nicely decouples the content from the view
- a Jinja2 template is also used to generate the status badge

In terms of usability, this PR improves several things:
- the main page is smaller and can be downloaded very fast
- the pages are generated using bootstrap 5, so they should adapt very well on different screen sizes
- the failures are displayed on top, so directly accessible without having to scroll through the whole page
- the stats are displayed in a separate tab, so also directly accessible

In terms of performance, generating the whole html output is probably not as fast as the master version (I haven't checked TBH) but it takes ~6s to parse the result.json file and to generate all html pages and badge.

This PR also requires changes in murdock-html and murdock code because the default url of the result is changed from "output.html" to "html/".

Since I couldn't really test everything and I could miss some things, there are a few unknowns:
- even if nightlies should be handled in the code changes, would they work ? (I only tested PRs)
- the "live" version of parse_result.py has been updated but is not tested
- other things ?

And of course I'm open to good UI ideas :)

**How to test this PR ?**

Here I provide the commands I used to test different use cases:

- PR with only builds, no error. I tested with https://github.com/RIOT-OS/RIOT/pull/16527
```
$ mkdir 16527 && cd 16527
$ echo 16527 > pull_nr
$ echo 130a03faf3d7b6a0e3c0181b7656709b0b33673d > pull_commit
$ wget https://ci.riot-os.org/RIOT-OS/RIOT/16527/130a03faf3d7b6a0e3c0181b7656709b0b33673d/output.txt
$ wget https://ci.riot-os.org/RIOT-OS/RIOT/16527/130a03faf3d7b6a0e3c0181b7656709b0b33673d/result.json
$ time SAVE_JOB_RESULTS=0 CI_PULL_NR=$(cat pull_nr) CI_PULL_COMMIT=$(cat pull_commit) <path-to>/murdock-scripts/parse_result.py static result.json output.txt

real	0m5,649s
user	0m5,230s
sys	0m0,397s
```

image

- PR with only builds, some errors. I tested with https://github.com/RIOT-OS/RIOT/pull/15030
```
$ mkdir 15030 && cd 15030
$ echo 15030 > pull_nr
$ echo ab9196a4fc65ccab26ceae0ceca4c263b7c16428 > pull_commit
$ wget https://ci.riot-os.org/RIOT-OS/RIOT/15030/ab9196a4fc65ccab26ceae0ceca4c263b7c16428/output.txt
$ wget https://ci.riot-os.org/RIOT-OS/RIOT/15030/ab9196a4fc65ccab26ceae0ceca4c263b7c16428/result.json
$ time SAVE_JOB_RESULTS=0 CI_PULL_NR=$(cat pull_nr) CI_PULL_COMMIT=$(cat pull_commit) <path-to>/murdock-scripts/parse_result.py static result.json output.txt

real	0m5,626s
user	0m5,133s
sys	0m0,451s
```

image

- PR with builds and tests, no error. I tested with https://github.com/RIOT-OS/RIOT/pull/16481
```
$ mkdir 16481 && cd 16481
$ echo 16481 > pull_nr
$ echo 7f8d3e198a4f24757b79a220d4d571e9beba03f7 > pull_commit
$ wget https://ci.riot-os.org/RIOT-OS/RIOT/16481/7f8d3e198a4f24757b79a220d4d571e9beba03f7/output.txt
$ wget https://ci.riot-os.org/RIOT-OS/RIOT/16481/7f8d3e198a4f24757b79a220d4d571e9beba03f7/result.json
$ time SAVE_JOB_RESULTS=0 CI_PULL_NR=$(cat pull_nr) CI_PULL_COMMIT=$(cat pull_commit) <path-to>/murdock-scripts/parse_result.py static result.json output.txt

real	0m6,953s
user	0m6,484s
sys	0m0,459s
```

image

- PR with builds and tests, with errors. I tested with https://github.com/RIOT-OS/RIOT/pull/15952
```
$ mkdir 15952 && cd 15952
$ echo 15952 > pull_nr
$ echo 63c9e3b8ecee1e00799ddc560ff7a106062c8251 > pull_commit
$ wget https://ci.riot-os.org/RIOT-OS/RIOT/15952/63c9e3b8ecee1e00799ddc560ff7a106062c8251/output.txt
$ wget https://ci.riot-os.org/RIOT-OS/RIOT/15952/63c9e3b8ecee1e00799ddc560ff7a106062c8251/result.json
$ time SAVE_JOB_RESULTS=0 CI_PULL_NR=$(cat pull_nr) CI_PULL_COMMIT=$(cat pull_commit) <path-to>/murdock-scripts/parse_result.py static result.json output.txt

real	0m6,529s
user	0m6,063s
sys	0m0,466s
```

image

- Invalid PR (cannot rebase), I tested with https://github.com/RIOT-OS/RIOT/pull/12665
```
$ mkdir 12665 && cd 12665
$ echo 12665 > pull_nr
$ echo 31488709a5e999f2f6db2789fc2cf4421111ece6 > pull_commit
$ wget https://ci.riot-os.org/RIOT-OS/RIOT/12665/31488709a5e999f2f6db2789fc2cf4421111ece6/output.txt
$ time SAVE_JOB_RESULTS=0 CI_PULL_NR=$(cat pull_nr) CI_PULL_COMMIT=$(cat pull_commit) <path-to>/murdock-scripts/parse_result.py static result.json output.txt

real	0m0,170s
user	0m0,147s
sys	0m0,024s
```

image

### CODE REVIEW

**Comment by aabadie** [comment]
With a bit of javascript, it's now also possible to filter the items displayed (depending on the context).

**Comment by kaspar030** [comment]
Could we introduce this staged?
I propose:
- let's not overwrite the current parse_results.py but add this PR's as a different file
- run both at the end of each build, with the new one outputting to a different (main) html, like, output_new.html.
- let the old one do the "live" view still
- let's watch the output for a while

then when happy, 
- drop the old one, making the new one the primary one.

As long as only files are added and a single extra script is called at the end of the build, I'm happy to quickly merge this and then watch it's output for a while. Directly replacing the current one, I'm not comfortable with, too much code in here.

**Comment by aabadie** [comment]
> Could we introduce this staged?

That sounds reasonable


> I propose:
>
>   let's not overwrite the current parse_results.py but add this PR's as a different file
>   run both at the end of each build, with the new one outputting to a different (main) html, like, output_new.html.
>   let the old one do the "live" view still
>   let's watch the output for a while

Should be easily doable, with some minor changes in the current PR. All html output is already written in a separate `html/` direcotry, the main page is `index.html` so can be reached with an url like `https://ci.riot-os.org/RIOT-OS/RIOT/<pr_num>/<pr_commit>/html`. If you don't mind I will keep the alive logic in the new script (it the same as the existing one, with minor improvements) because they share some code (for writing the text files containing the command outputs).

**Comment by aabadie** [comment]
So I pushed a version of this PR that should allow a staged integration. There are other things that were added/improved compared to the original version of this PR:
- a search field is added in several place to filter failed jobs and applications (because the list can be large)
- the title of the pages contains information on the results (which PR, success/failed icon, etc)
- each application html page is generated in parallel (using Python multiprocessing), because this is where the time is spent the most. The performance speed is not very important but it saves a few seconds and it should scale better I think.

Another point that is to consider is the disk usage of generated files: html is quite verbose and there are a lot files generated. The usage of a run with only builds is 95MB, for a run with tests it's 98MB. I think that in the current state (all results in a single page), it takes 16MB.

**Comment by aabadie** [comment]
Another thing to consider: the Python version on the server running Murdock should be Python 3.6 at least (for sorted dicts, f-string are not used but could).

**Comment by aabadie** [comment]
Here are a few numbers (with an updated version of the command to generate the output):

```
for pr in 12665 15030 15952 16481 16527; do echo;echo -- PR \#${pr};cd ${pr};time SAVE_JOB_RESULTS=0 LOCAL_TESTING=1 CI_PULL_NR=$(cat pull_nr) CI_PULL_COMMIT=$(cat pull_commit) /work/riot/murdock-scripts/generate_output.py static result.json output.txt;echo;du -sh html/;echo;cd ..;echo --done;echo; done

-- PR #12665

real	0m0,190s
user	0m0,154s
sys	0m0,042s

20K	html/

--done


-- PR #15030

real	0m7,069s
user	0m15,933s
sys	0m2,702s

89M	html/

--done


-- PR #15952

real	0m10,737s
user	0m39,615s
sys	0m4,473s

90M	html/

--done


-- PR #16481

real	0m10,963s
user	0m40,140s
sys	0m4,600s

90M	html/

--done


-- PR #16527

real	0m9,531s
user	0m32,582s
sys	0m3,664s

87M	html/

--done

```

The latest version of this PR contains templates with less spaces to reduce the disk usage.

**Comment by fjmolinas** [comment]
@kaspar030 is this in a state to be tested out now?

**Comment by aabadie** [comment]
I prefer that we wait for https://github.com/RIOT-OS/murdock-html/pull/18 where I went for bootstrap-icons finally and I'd like to reuse the same icons here (this PR is using fontawesome for the moment).

**Comment by aabadie** [comment]
> I prefer that we wait for RIOT-OS/murdock-html#18 where I went for bootstrap-icons finally and I'd like to reuse the same icons here 

I'm done with this one as well (but still prefer to have RIOT-OS/murdock-html#18 being deployed first to have consistent styles/layouts).
In the meantime, some improvements were added to this PR:
- several bugs fixed and size optimizations in the html templates
- integrate an [html minifier](https://pypi.org/project/minify-html/) to use less disk space. Another advantage of this tool is that it checks the validity of the generated html. There's a small speed penalty ~1s out of 8.

Overall the improvement is significant: from ~90MB to 55MB for the whole generated html files. It's still more than the actual single html file but comes with a more user friendly interface.

<details><summary>some numbers</summary>

```
for pr in 12665 15030 15952 16481 16527; do echo;echo -- PR \#${pr};cd ${pr};time SAVE_JOB_RESULTS=0 LOCAL_TESTING=1 CI_PULL_NR=$(cat pull_nr) CI_PULL_COMMIT=$(cat pull_commit) /work/riot/murdock-scripts/generate_output.py static result.json output.txt;echo;du -sh html/;echo;cd ..;echo --done;echo; done

-- PR #12665

real	0m0,183s
user	0m0,144s
sys	0m0,046s

20K	html/

--done


-- PR #15030

real	0m8,145s
user	0m18,241s
sys	0m2,973s

54M	html/

--done


-- PR #15952

real	0m9,140s
user	0m22,802s
sys	0m3,483s

56M	html/

--done


-- PR #16481

real	0m9,302s
user	0m24,028s
sys	0m3,631s

56M	html/

--done


-- PR #16527

real	0m8,321s
user	0m19,354s
sys	0m3,039s

53M	html/

--done
```

</details>

**Comment by miri64** [comment]
> I'm done with this one as well (but still prefer to have [RIOT-OS/murdock-html#18](https://github.com/RIOT-OS/murdock-html/pull/18) being deployed first to have consistent styles/layouts).

Not to sway any opinion, but if Google, Facebook, Twitter and the like can do that, I think we can live with an inconsistent layout within our CI system for a few month (case and point: look at Jenkins and Blue Ocean...). This PR is far more manageable to review than RIOT-OS/murdock-html#18, so RIOT-OS/murdock-html#18 should not be a blocker, as this PR actually increases the usability of our CI.

**Comment by aabadie** [comment]
> This PR is far more manageable to review than RIOT-OS/murdock-html#18, so RIOT-OS/murdock-html#18 should not be a blocker, as this PR actually increases the usability of our CI.

I agree :)

**Comment by aabadie** [comment]
Just note that there's a dependency to [minify-html](https://pypi.org/project/minify-html/) which is a prebuilt tool written in Rust. It's installed via pip and binaries are available for Linux, MacOS and Windows. I hope this won't be a problem with the server running the murdock script (I guess it's Linux but not sure).

**Comment by aabadie** [comment]
Any chance that this PR could be tested soonish with Murdock ?

**Comment by aabadie** [comment]
I'm closing this PR: it's now useless with the newest version of https://github.com/RIOT-OS/murdock-html/pull/19 where results are fetched and rendered on demand by the React application.

**Pull request closed without merging**
