### PR TITLE
Adapt scripts to new Murdock API

### PR DESCRIPTION
**Pull request by aabadie**
This PR adapts the interaction of the build.sh with the Murdock backend rewrite provided in https://github.com/kaspar030/murdock/pull/30

Each job now has a unique identifier, is authenticated using a token and the REST API endpoint has changed. So the live update logic is adapted to be compatible.

Other potential updates (not provided here):
- Allow to build a branch, since the Murdock backend rewrite allows that
- Rename build.sh in run.sh since the build.sh script does more than just building: it can also run tests
- Better categorize failures: now there's only failed jobs and it would be better to fave failed builds/failed tests groups. This will allow to improve the UI.

Related PR: https://github.com/kaspar030/murdock/pull/30

### CODE REVIEW

**Comment by aabadie** [comment]
> Better categorize failures: now there's only failed jobs and it would be better to fave failed builds/failed tests groups. This will allow to improve the UI.

I added some code to handle that here. The PRs related in murdock and murdock-html are adapted as well.

**Comment by aabadie** [comment]
A Dockerfile is also added: it can be used as Docker image for the murdock webapp backend and should contain necessary tools used by the build.sh script.

**Comment by aabadie** [comment]
Pushed two commits to revert #37

**Comment by kaspar030** [comment]
I've merged this into "murdock_rewrite"!

**Pull request merged**
