### PR TITLE
add merge group CI_BASE_BRANCH/COMMIT extraction

### PR DESCRIPTION
**Pull request by kaspar030**

### CODE REVIEW

**Comment by kaspar030** [comment]
I've deployed this to `latest-staging`, testing now.

**Comment by kaspar030** [comment]
seems to not break anything, and the info is extracted properly.
here's a merge_group build: https://ci-staging.riot-os.org/details/325300c6e415461e8d75df0d6051d9f5/output
here's a non merge_group build: https://ci-staging.riot-os.org/details/7308581f2a4e45c28b03978acf7076ca/output

**Comment by kaspar030** [comment]
@MrKevinWeiss @aabadie do you think you could ACK this?

**Review by MrKevinWeiss — APPROVED** [review]
We need a solution so let's try it!

**Pull request merged**
