### PR TITLE
update to distributed murdock

### PR DESCRIPTION
**Pull request by kaspar030**
Production Murdock has been using the scripts from this branch for months, so I think it is about time to merge them here.

### CODE REVIEW

**Comment by smlng** [comment]
ACK, care to squash?

**Comment by kaspar030** [comment]
> ACK, care to squash?

You mean like, squash them all in one commit? Actually I'd like to keep the history...

**Comment by smlng** [comment]
well not all into one, but sensible like 

```
README.md: add pytoml dependency a9b378e
update README.md dc7e479
update README.md daaf203
```

into one

**Comment by smlng** [comment]
but on the other hand its not that important here.

**Comment by kaspar030** [comment]
> but on the other hand its not that important here.

I squashed the (IMO) most obvoious. Feel free to merge as is (or use github's "squash merge", I don't really care. :) ).

**Comment by smlng** [comment]
@kaspar030 sadly I don't have write access to this repo 😢 can't merge ...

**Comment by kaspar030** [comment]
> sadly I don't have write access to this repo 😢 can't merge ...

Oh. Can you try again? I've added the CI admin group as admin.

**Comment by smlng** [comment]
done!

**Pull request merged**
